#Arduino Scale Configuration
#Tue Jun 02 03:13:11 JST 2026
historyDbUrl=jdbc\:sqlite\:/REC.db
studentDbUrl=jdbc\:sqlite\:/STDID.db
scaleFactor=208.0
bPortName=COM4
aPortName=COM3
historyTable=waste_records
tareValue=255550
